apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: registry.solar.com.py/bancadigital/core/commons-api-service
  newTag: 6d73c332
